# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08222246f425ac2d0d20f0bc8df6c3f17bb05975037ec3cdf01bfd4fc0b7b38bdb2dfe6d4f1fe5db02e031376fd3e46629cdf1cbc9acf04eab1af001bd677848

test:
  secret_key_base: 8db46b85ed9165ac965cda6a95b9021c6758c1c0ba31d4efca18911317f6f016d89abac1c0a368345f316acea72f60521cc27f2971ec1a19ca3ba536ed134240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
